
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ../dbdata:/var/lib/postgresql/data
      - ../data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network
  warehouse_db:
    image: postgres:12
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: stefano
      POSTGRES_PASSWORD: stefanovivas
      PGPORT: 5433
    volumes:
      - ./dbdata_ecommerce:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5433
    networks:
      - postgres-compose-network  
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin2023"
    ports:
      - "16543:80"
    depends_on:
      - db
      - warehouse_db
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge